### ISSUE TITLE
Cannot make https working

### ISSUE THREAD

**Issue by a-litvin** [PrestaShop/prestashop-flashlight#131]
Him

I tried both PS_PROTOCOL and SSL_REDIRECT together and individually. When I'm trying to reach the site, I'm getting ERR_CONNECTION_CLOSED. It seems it never reaches Presta.

In nginx in /etc/nginx.nginx.conf I see, that it doesn't listen to 443 port, so I don't see how it can be working.

Here's my docker-compose.yml:

```
services:
  prestashop:
    image: prestashop/prestashop-flashlight:1.7.8.11
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PS_DOMAIN=localhost
      - PS_PROTOCOL=https
      - SSL_REDIRECT=true
      - DEBUG_MODE=true
      - XDEBUG_ENABLED=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:cached

  mysql:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
```

What's missing?
