### ISSUE TITLE
Using Prestashop Flashlight to launch tests

### ISSUE THREAD

**Issue by Maus3rSR** [PrestaShop/prestashop-flashlight#136]
Hello

Thank you for first awesome docker image that let us able to run an instance of Prestashop in seconds and install our modules for development purposes.

I would also like to use this image to launch my Integration test. However how can I achieve this goal as the Prestashop code source zip used in the image is a production build and does not contain any testing?

I like to practice TDD, DI, IoC etc. And I really enjoy developing 90% of my module without having to test each time by launching the browser, going to admin, login, goto thing, etc.

I show you the simple thing I try to achieve:

My docker compose
```yaml
name: $MODULE
services:
  prestashop:
    image: prestashop/prestashop-flashlight:latest
    container_name: $MODULE-ps
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MODULE_NAME: $MODULE
      PS_DOMAIN: localhost:8000
      INIT_SCRIPTS_DIR: /tmp/init-scripts
    ports:
      - 8000:80
    volumes:
      - ./scripts:/tmp/init-scripts:ro
      - type: bind
        source: ../modules/$MODULE
        target: /var/www/html/modules/$MODULE

  mysql:
    image: mariadb:lts
    container_name: $MODULE-db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 20s
      retries: 5
    environment:
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
```

in modules/gtrmanager/composer.json

```json
"gtrmanager:test:unit": "docker exec gtrmanager-ps /usr/bin/phpunit -c modules/gtrmanager/tests/Unit/phpunit.xml",
"gtrmanager:test:integration": "docker exec gtrmanager-ps /usr/bin/phpunit -c modules/gtrmanager/tests/Integration/phpunit.xml"
```

In modules/gtrmanager/tests/Integration/phpunit.xml and bootstrap.php
```xml
<phpunit backupGlobals="false" colors="true" bootstrap="bootstrap.php" cacheDirectory=".phpunit.cache" processIsolation="true">
    <php>
        <env name="KERNEL_CLASS" value="AppKernel" />
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak"/>
    </php>
    <testsuites>
        <testsuite name="Integration">
            <directory>.</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory>../../src</directory>
        </include>
    </source>
</phpunit>
```

```php
<?php

define('_PS_IN_TEST_', true);
define('_PS_ROOT_DIR_', dirname(__DIR__, 4));
define('_PS_MODULE_DIR_', _PS_ROOT_DIR_ . '/modules/');

require_once _PS_ROOT_DIR_ . '/admin-dev/bootstrap.php';
require_once _PS_MODULE_DIR_ . '/gtrmanager/vendor/autoload.php';
```

And my test file

```php
<?php

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\HttpFoundation\Response;


/**
 * @testdox Configuration page
 */
class ConfigurationTest extends WebTestCase
{
    protected KernelBrowser $client;
    protected Router $router;

    protected function setUp(): void
    {
        parent::setUp();
        $this->client = self::createClient();
        $this->router = self::$kernel->getContainer()->get('router');
    }

    /**
     * @test
     * @testdox should be displayed
     */
    public function shouldDisplayConfigurationPage(): void
    {
        $url = $this->router->generate('gtrmanager_configuration');
        $this->client->request('GET', $url);
        $response = $this->client->getResponse();

        $this->assertEquals(Response::HTTP_OK, $response->getStatusCode());
    }
}
```

Im getting hard times running this simple code because when running the test Im going into the test context and Prestashop manage to load test config, using test_databasename, etc. However all these things are missing in a production sourcecode.

How can I achieve that?
